# Generated by Django 3.2.9 on 2021-12-17 18:34

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип действия',
                'verbose_name_plural': 'Типы действий',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги для изображений',
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название поста')),
                ('pubdate', models.DateField(verbose_name='Дата события')),
                ('register_date', models.DateField(auto_now=True)),
                ('studio_name', models.CharField(blank=True, default='Текущая', max_length=150, verbose_name='Название студии (если это "новость")')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст статьи')),
                ('small_description', tinymce.models.HTMLField(blank=True, verbose_name='Небольшое описание мероприятия')),
                ('preview_image', models.ImageField(upload_to='posts/', verbose_name='Основное изображение поста')),
                ('type', models.ManyToManyField(blank=True, related_name='actions', to='news.ActionType')),
            ],
            options={
                'verbose_name': 'Новостной пост',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('video', models.CharField(blank=True, max_length=400, null=True)),
                ('text_under', tinymce.models.HTMLField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newspost')),
                ('tag', models.ManyToManyField(blank=True, related_name='images', to='news.Tag')),
            ],
            options={
                'verbose_name': 'Изображение или видео для поста',
                'verbose_name_plural': 'Изображения или видео',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('pubdate', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('author_email', models.EmailField(max_length=120, verbose_name='Mail пользователя')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newspost')),
            ],
            options={
                'verbose_name': 'Комментарий к посту',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
